title: harsha first
description: very excited to create
template:
  repo: harsha-first-template
  name: harsha-first
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
